# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wheelofjeopardy/gui/pyqt/ui_category_choice_popup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CategoryChoicePopup(object):
    def setupUi(self, CategoryChoicePopup):
        CategoryChoicePopup.setObjectName(_fromUtf8("CategoryChoicePopup"))
        CategoryChoicePopup.resize(749, 203)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(CategoryChoicePopup)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.titleLabel = QtGui.QLabel(CategoryChoicePopup)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout.addWidget(self.titleLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.category1Label = QtGui.QLabel(CategoryChoicePopup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1Label.sizePolicy().hasHeightForWidth())
        self.category1Label.setSizePolicy(sizePolicy)
        self.category1Label.setMinimumSize(QtCore.QSize(100, 100))
        self.category1Label.setMaximumSize(QtCore.QSize(100, 100))
        self.category1Label.setFrameShape(QtGui.QFrame.Box)
        self.category1Label.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1Label.setLineWidth(2)
        self.category1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.category1Label.setWordWrap(True)
        self.category1Label.setObjectName(_fromUtf8("category1Label"))
        self.horizontalLayout_2.addWidget(self.category1Label)
        self.category2Label = QtGui.QLabel(CategoryChoicePopup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2Label.sizePolicy().hasHeightForWidth())
        self.category2Label.setSizePolicy(sizePolicy)
        self.category2Label.setMinimumSize(QtCore.QSize(100, 100))
        self.category2Label.setMaximumSize(QtCore.QSize(100, 100))
        self.category2Label.setFrameShape(QtGui.QFrame.Box)
        self.category2Label.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2Label.setLineWidth(2)
        self.category2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.category2Label.setWordWrap(True)
        self.category2Label.setObjectName(_fromUtf8("category2Label"))
        self.horizontalLayout_2.addWidget(self.category2Label)
        self.category3Label = QtGui.QLabel(CategoryChoicePopup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3Label.sizePolicy().hasHeightForWidth())
        self.category3Label.setSizePolicy(sizePolicy)
        self.category3Label.setMinimumSize(QtCore.QSize(100, 100))
        self.category3Label.setMaximumSize(QtCore.QSize(100, 100))
        self.category3Label.setFrameShape(QtGui.QFrame.Box)
        self.category3Label.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3Label.setLineWidth(2)
        self.category3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.category3Label.setWordWrap(True)
        self.category3Label.setObjectName(_fromUtf8("category3Label"))
        self.horizontalLayout_2.addWidget(self.category3Label)
        self.category4Label = QtGui.QLabel(CategoryChoicePopup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4Label.sizePolicy().hasHeightForWidth())
        self.category4Label.setSizePolicy(sizePolicy)
        self.category4Label.setMinimumSize(QtCore.QSize(100, 100))
        self.category4Label.setMaximumSize(QtCore.QSize(100, 100))
        self.category4Label.setFrameShape(QtGui.QFrame.Box)
        self.category4Label.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4Label.setLineWidth(2)
        self.category4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.category4Label.setWordWrap(True)
        self.category4Label.setObjectName(_fromUtf8("category4Label"))
        self.horizontalLayout_2.addWidget(self.category4Label)
        self.category5Label = QtGui.QLabel(CategoryChoicePopup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5Label.sizePolicy().hasHeightForWidth())
        self.category5Label.setSizePolicy(sizePolicy)
        self.category5Label.setMinimumSize(QtCore.QSize(100, 100))
        self.category5Label.setMaximumSize(QtCore.QSize(100, 100))
        self.category5Label.setFrameShape(QtGui.QFrame.Box)
        self.category5Label.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5Label.setLineWidth(2)
        self.category5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.category5Label.setWordWrap(True)
        self.category5Label.setObjectName(_fromUtf8("category5Label"))
        self.horizontalLayout_2.addWidget(self.category5Label)
        self.category6Label = QtGui.QLabel(CategoryChoicePopup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6Label.sizePolicy().hasHeightForWidth())
        self.category6Label.setSizePolicy(sizePolicy)
        self.category6Label.setMinimumSize(QtCore.QSize(100, 100))
        self.category6Label.setMaximumSize(QtCore.QSize(100, 100))
        self.category6Label.setFrameShape(QtGui.QFrame.Box)
        self.category6Label.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6Label.setLineWidth(2)
        self.category6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.category6Label.setWordWrap(True)
        self.category6Label.setObjectName(_fromUtf8("category6Label"))
        self.horizontalLayout_2.addWidget(self.category6Label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.category1 = QtGui.QPushButton(CategoryChoicePopup)
        self.category1.setObjectName(_fromUtf8("category1"))
        self.horizontalLayout.addWidget(self.category1)
        self.category2 = QtGui.QPushButton(CategoryChoicePopup)
        self.category2.setObjectName(_fromUtf8("category2"))
        self.horizontalLayout.addWidget(self.category2)
        self.category3 = QtGui.QPushButton(CategoryChoicePopup)
        self.category3.setObjectName(_fromUtf8("category3"))
        self.horizontalLayout.addWidget(self.category3)
        self.category4 = QtGui.QPushButton(CategoryChoicePopup)
        self.category4.setObjectName(_fromUtf8("category4"))
        self.horizontalLayout.addWidget(self.category4)
        self.category5 = QtGui.QPushButton(CategoryChoicePopup)
        self.category5.setObjectName(_fromUtf8("category5"))
        self.horizontalLayout.addWidget(self.category5)
        self.category6 = QtGui.QPushButton(CategoryChoicePopup)
        self.category6.setObjectName(_fromUtf8("category6"))
        self.horizontalLayout.addWidget(self.category6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(CategoryChoicePopup)
        QtCore.QObject.connect(self.category1, QtCore.SIGNAL(_fromUtf8("clicked()")), CategoryChoicePopup.close)
        QtCore.QObject.connect(self.category2, QtCore.SIGNAL(_fromUtf8("clicked()")), CategoryChoicePopup.close)
        QtCore.QObject.connect(self.category3, QtCore.SIGNAL(_fromUtf8("clicked()")), CategoryChoicePopup.close)
        QtCore.QObject.connect(self.category4, QtCore.SIGNAL(_fromUtf8("clicked()")), CategoryChoicePopup.close)
        QtCore.QObject.connect(self.category5, QtCore.SIGNAL(_fromUtf8("clicked()")), CategoryChoicePopup.close)
        QtCore.QObject.connect(self.category6, QtCore.SIGNAL(_fromUtf8("clicked()")), CategoryChoicePopup.close)
        QtCore.QMetaObject.connectSlotsByName(CategoryChoicePopup)

    def retranslateUi(self, CategoryChoicePopup):
        CategoryChoicePopup.setWindowTitle(_translate("CategoryChoicePopup", "Dialog", None))
        self.titleLabel.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category1Label.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category2Label.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category3Label.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category4Label.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category5Label.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category6Label.setText(_translate("CategoryChoicePopup", "TextLabel", None))
        self.category1.setText(_translate("CategoryChoicePopup", "Category 1", None))
        self.category2.setText(_translate("CategoryChoicePopup", "Category 2", None))
        self.category3.setText(_translate("CategoryChoicePopup", "Category 3", None))
        self.category4.setText(_translate("CategoryChoicePopup", "Category 4", None))
        self.category5.setText(_translate("CategoryChoicePopup", "Category 5", None))
        self.category6.setText(_translate("CategoryChoicePopup", "Category 6", None))
