# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wheelofjeopardy/gui/pyqt/ui_woj_application_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WojApplicationWindow(object):
    def setupUi(self, WojApplicationWindow):
        WojApplicationWindow.setObjectName(_fromUtf8("WojApplicationWindow"))
        WojApplicationWindow.resize(1000, 840)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WojApplicationWindow.sizePolicy().hasHeightForWidth())
        WojApplicationWindow.setSizePolicy(sizePolicy)
        WojApplicationWindow.setMinimumSize(QtCore.QSize(1000, 820))
        WojApplicationWindow.setMaximumSize(QtCore.QSize(1030, 840))
        self.centralwidget = QtGui.QWidget(WojApplicationWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.questionsContestantsLayout = QtGui.QVBoxLayout()
        self.questionsContestantsLayout.setObjectName(_fromUtf8("questionsContestantsLayout"))
        self.applicationTitle = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.applicationTitle.setFont(font)
        self.applicationTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationTitle.setObjectName(_fromUtf8("applicationTitle"))
        self.questionsContestantsLayout.addWidget(self.applicationTitle)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.questionsContestantsLayout.addItem(spacerItem)
        self.jeopardyMatrix = QtGui.QFrame(self.centralwidget)
        self.jeopardyMatrix.setMinimumSize(QtCore.QSize(600, 310))
        self.jeopardyMatrix.setMaximumSize(QtCore.QSize(600, 800))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.jeopardyMatrix.setFont(font)
        self.jeopardyMatrix.setFrameShape(QtGui.QFrame.Box)
        self.jeopardyMatrix.setFrameShadow(QtGui.QFrame.Sunken)
        self.jeopardyMatrix.setLineWidth(3)
        self.jeopardyMatrix.setObjectName(_fromUtf8("jeopardyMatrix"))
        self.gridLayout_2 = QtGui.QGridLayout(self.jeopardyMatrix)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.category2Cell3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2Cell3.sizePolicy().hasHeightForWidth())
        self.category2Cell3.setSizePolicy(sizePolicy)
        self.category2Cell3.setMinimumSize(QtCore.QSize(80, 40))
        self.category2Cell3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category2Cell3.setFont(font)
        self.category2Cell3.setFrameShape(QtGui.QFrame.Box)
        self.category2Cell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2Cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.category2Cell3.setObjectName(_fromUtf8("category2Cell3"))
        self.gridLayout_2.addWidget(self.category2Cell3, 4, 1, 1, 1)
        self.category6Cell5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6Cell5.sizePolicy().hasHeightForWidth())
        self.category6Cell5.setSizePolicy(sizePolicy)
        self.category6Cell5.setMinimumSize(QtCore.QSize(80, 40))
        self.category6Cell5.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category6Cell5.setFont(font)
        self.category6Cell5.setFrameShape(QtGui.QFrame.Box)
        self.category6Cell5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6Cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.category6Cell5.setObjectName(_fromUtf8("category6Cell5"))
        self.gridLayout_2.addWidget(self.category6Cell5, 6, 5, 1, 1)
        self.category2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2.sizePolicy().hasHeightForWidth())
        self.category2.setSizePolicy(sizePolicy)
        self.category2.setMinimumSize(QtCore.QSize(80, 50))
        self.category2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.category2.setFont(font)
        self.category2.setFrameShape(QtGui.QFrame.Box)
        self.category2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2.setScaledContents(True)
        self.category2.setAlignment(QtCore.Qt.AlignCenter)
        self.category2.setWordWrap(True)
        self.category2.setIndent(1)
        self.category2.setObjectName(_fromUtf8("category2"))
        self.gridLayout_2.addWidget(self.category2, 0, 1, 1, 1)
        self.category6 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6.sizePolicy().hasHeightForWidth())
        self.category6.setSizePolicy(sizePolicy)
        self.category6.setMinimumSize(QtCore.QSize(80, 50))
        self.category6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.category6.setFont(font)
        self.category6.setFrameShape(QtGui.QFrame.Box)
        self.category6.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6.setScaledContents(True)
        self.category6.setAlignment(QtCore.Qt.AlignCenter)
        self.category6.setWordWrap(True)
        self.category6.setIndent(1)
        self.category6.setObjectName(_fromUtf8("category6"))
        self.gridLayout_2.addWidget(self.category6, 0, 5, 1, 1)
        self.category5Cell5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5Cell5.sizePolicy().hasHeightForWidth())
        self.category5Cell5.setSizePolicy(sizePolicy)
        self.category5Cell5.setMinimumSize(QtCore.QSize(80, 40))
        self.category5Cell5.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category5Cell5.setFont(font)
        self.category5Cell5.setFrameShape(QtGui.QFrame.Box)
        self.category5Cell5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5Cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.category5Cell5.setObjectName(_fromUtf8("category5Cell5"))
        self.gridLayout_2.addWidget(self.category5Cell5, 6, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.jeopardyMatrix)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 6)
        self.category3Cell5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3Cell5.sizePolicy().hasHeightForWidth())
        self.category3Cell5.setSizePolicy(sizePolicy)
        self.category3Cell5.setMinimumSize(QtCore.QSize(80, 40))
        self.category3Cell5.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category3Cell5.setFont(font)
        self.category3Cell5.setFrameShape(QtGui.QFrame.Box)
        self.category3Cell5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3Cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.category3Cell5.setObjectName(_fromUtf8("category3Cell5"))
        self.gridLayout_2.addWidget(self.category3Cell5, 6, 2, 1, 1)
        self.category4Cell1 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4Cell1.sizePolicy().hasHeightForWidth())
        self.category4Cell1.setSizePolicy(sizePolicy)
        self.category4Cell1.setMinimumSize(QtCore.QSize(80, 40))
        self.category4Cell1.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category4Cell1.setFont(font)
        self.category4Cell1.setFrameShape(QtGui.QFrame.Box)
        self.category4Cell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4Cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.category4Cell1.setObjectName(_fromUtf8("category4Cell1"))
        self.gridLayout_2.addWidget(self.category4Cell1, 2, 3, 1, 1)
        self.category3Cell1 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3Cell1.sizePolicy().hasHeightForWidth())
        self.category3Cell1.setSizePolicy(sizePolicy)
        self.category3Cell1.setMinimumSize(QtCore.QSize(80, 40))
        self.category3Cell1.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category3Cell1.setFont(font)
        self.category3Cell1.setFrameShape(QtGui.QFrame.Box)
        self.category3Cell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3Cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.category3Cell1.setObjectName(_fromUtf8("category3Cell1"))
        self.gridLayout_2.addWidget(self.category3Cell1, 2, 2, 1, 1)
        self.category2Cell1 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2Cell1.sizePolicy().hasHeightForWidth())
        self.category2Cell1.setSizePolicy(sizePolicy)
        self.category2Cell1.setMinimumSize(QtCore.QSize(80, 40))
        self.category2Cell1.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category2Cell1.setFont(font)
        self.category2Cell1.setFrameShape(QtGui.QFrame.Box)
        self.category2Cell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2Cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.category2Cell1.setObjectName(_fromUtf8("category2Cell1"))
        self.gridLayout_2.addWidget(self.category2Cell1, 2, 1, 1, 1)
        self.category1Cell3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1Cell3.sizePolicy().hasHeightForWidth())
        self.category1Cell3.setSizePolicy(sizePolicy)
        self.category1Cell3.setMinimumSize(QtCore.QSize(80, 40))
        self.category1Cell3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category1Cell3.setFont(font)
        self.category1Cell3.setFrameShape(QtGui.QFrame.Box)
        self.category1Cell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1Cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.category1Cell3.setObjectName(_fromUtf8("category1Cell3"))
        self.gridLayout_2.addWidget(self.category1Cell3, 4, 0, 1, 1)
        self.category4Cell5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4Cell5.sizePolicy().hasHeightForWidth())
        self.category4Cell5.setSizePolicy(sizePolicy)
        self.category4Cell5.setMinimumSize(QtCore.QSize(80, 40))
        self.category4Cell5.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category4Cell5.setFont(font)
        self.category4Cell5.setFrameShape(QtGui.QFrame.Box)
        self.category4Cell5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4Cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.category4Cell5.setObjectName(_fromUtf8("category4Cell5"))
        self.gridLayout_2.addWidget(self.category4Cell5, 6, 3, 1, 1)
        self.category4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4.sizePolicy().hasHeightForWidth())
        self.category4.setSizePolicy(sizePolicy)
        self.category4.setMinimumSize(QtCore.QSize(80, 50))
        self.category4.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.category4.setFont(font)
        self.category4.setFrameShape(QtGui.QFrame.Box)
        self.category4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4.setScaledContents(True)
        self.category4.setAlignment(QtCore.Qt.AlignCenter)
        self.category4.setWordWrap(True)
        self.category4.setIndent(1)
        self.category4.setObjectName(_fromUtf8("category4"))
        self.gridLayout_2.addWidget(self.category4, 0, 3, 1, 1)
        self.category4Cell3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4Cell3.sizePolicy().hasHeightForWidth())
        self.category4Cell3.setSizePolicy(sizePolicy)
        self.category4Cell3.setMinimumSize(QtCore.QSize(80, 40))
        self.category4Cell3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category4Cell3.setFont(font)
        self.category4Cell3.setFrameShape(QtGui.QFrame.Box)
        self.category4Cell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4Cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.category4Cell3.setObjectName(_fromUtf8("category4Cell3"))
        self.gridLayout_2.addWidget(self.category4Cell3, 4, 3, 1, 1)
        self.category1Cell5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1Cell5.sizePolicy().hasHeightForWidth())
        self.category1Cell5.setSizePolicy(sizePolicy)
        self.category1Cell5.setMinimumSize(QtCore.QSize(80, 40))
        self.category1Cell5.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category1Cell5.setFont(font)
        self.category1Cell5.setFrameShape(QtGui.QFrame.Box)
        self.category1Cell5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1Cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.category1Cell5.setObjectName(_fromUtf8("category1Cell5"))
        self.gridLayout_2.addWidget(self.category1Cell5, 6, 0, 1, 1)
        self.category5Cell3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5Cell3.sizePolicy().hasHeightForWidth())
        self.category5Cell3.setSizePolicy(sizePolicy)
        self.category5Cell3.setMinimumSize(QtCore.QSize(80, 40))
        self.category5Cell3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category5Cell3.setFont(font)
        self.category5Cell3.setFrameShape(QtGui.QFrame.Box)
        self.category5Cell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5Cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.category5Cell3.setObjectName(_fromUtf8("category5Cell3"))
        self.gridLayout_2.addWidget(self.category5Cell3, 4, 4, 1, 1)
        self.category4Cell2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4Cell2.sizePolicy().hasHeightForWidth())
        self.category4Cell2.setSizePolicy(sizePolicy)
        self.category4Cell2.setMinimumSize(QtCore.QSize(80, 40))
        self.category4Cell2.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category4Cell2.setFont(font)
        self.category4Cell2.setFrameShape(QtGui.QFrame.Box)
        self.category4Cell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4Cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.category4Cell2.setObjectName(_fromUtf8("category4Cell2"))
        self.gridLayout_2.addWidget(self.category4Cell2, 3, 3, 1, 1)
        self.category1Cell2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1Cell2.sizePolicy().hasHeightForWidth())
        self.category1Cell2.setSizePolicy(sizePolicy)
        self.category1Cell2.setMinimumSize(QtCore.QSize(80, 40))
        self.category1Cell2.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category1Cell2.setFont(font)
        self.category1Cell2.setFrameShape(QtGui.QFrame.Box)
        self.category1Cell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1Cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.category1Cell2.setObjectName(_fromUtf8("category1Cell2"))
        self.gridLayout_2.addWidget(self.category1Cell2, 3, 0, 1, 1)
        self.category2Cell4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2Cell4.sizePolicy().hasHeightForWidth())
        self.category2Cell4.setSizePolicy(sizePolicy)
        self.category2Cell4.setMinimumSize(QtCore.QSize(80, 40))
        self.category2Cell4.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category2Cell4.setFont(font)
        self.category2Cell4.setFrameShape(QtGui.QFrame.Box)
        self.category2Cell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2Cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.category2Cell4.setObjectName(_fromUtf8("category2Cell4"))
        self.gridLayout_2.addWidget(self.category2Cell4, 5, 1, 1, 1)
        self.category6Cell4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6Cell4.sizePolicy().hasHeightForWidth())
        self.category6Cell4.setSizePolicy(sizePolicy)
        self.category6Cell4.setMinimumSize(QtCore.QSize(80, 40))
        self.category6Cell4.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category6Cell4.setFont(font)
        self.category6Cell4.setFrameShape(QtGui.QFrame.Box)
        self.category6Cell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6Cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.category6Cell4.setObjectName(_fromUtf8("category6Cell4"))
        self.gridLayout_2.addWidget(self.category6Cell4, 5, 5, 1, 1)
        self.category1Cell1 = QtGui.QLabel(self.jeopardyMatrix)
        self.category1Cell1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1Cell1.sizePolicy().hasHeightForWidth())
        self.category1Cell1.setSizePolicy(sizePolicy)
        self.category1Cell1.setMinimumSize(QtCore.QSize(80, 40))
        self.category1Cell1.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category1Cell1.setFont(font)
        self.category1Cell1.setFrameShape(QtGui.QFrame.Box)
        self.category1Cell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1Cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.category1Cell1.setObjectName(_fromUtf8("category1Cell1"))
        self.gridLayout_2.addWidget(self.category1Cell1, 2, 0, 1, 1)
        self.category1Cell4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1Cell4.sizePolicy().hasHeightForWidth())
        self.category1Cell4.setSizePolicy(sizePolicy)
        self.category1Cell4.setMinimumSize(QtCore.QSize(80, 40))
        self.category1Cell4.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category1Cell4.setFont(font)
        self.category1Cell4.setFrameShape(QtGui.QFrame.Box)
        self.category1Cell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1Cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.category1Cell4.setObjectName(_fromUtf8("category1Cell4"))
        self.gridLayout_2.addWidget(self.category1Cell4, 5, 0, 1, 1)
        self.category5Cell2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5Cell2.sizePolicy().hasHeightForWidth())
        self.category5Cell2.setSizePolicy(sizePolicy)
        self.category5Cell2.setMinimumSize(QtCore.QSize(80, 40))
        self.category5Cell2.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category5Cell2.setFont(font)
        self.category5Cell2.setFrameShape(QtGui.QFrame.Box)
        self.category5Cell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5Cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.category5Cell2.setObjectName(_fromUtf8("category5Cell2"))
        self.gridLayout_2.addWidget(self.category5Cell2, 3, 4, 1, 1)
        self.category3Cell2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3Cell2.sizePolicy().hasHeightForWidth())
        self.category3Cell2.setSizePolicy(sizePolicy)
        self.category3Cell2.setMinimumSize(QtCore.QSize(80, 40))
        self.category3Cell2.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category3Cell2.setFont(font)
        self.category3Cell2.setFrameShape(QtGui.QFrame.Box)
        self.category3Cell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3Cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.category3Cell2.setObjectName(_fromUtf8("category3Cell2"))
        self.gridLayout_2.addWidget(self.category3Cell2, 3, 2, 1, 1)
        self.category6Cell3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6Cell3.sizePolicy().hasHeightForWidth())
        self.category6Cell3.setSizePolicy(sizePolicy)
        self.category6Cell3.setMinimumSize(QtCore.QSize(80, 40))
        self.category6Cell3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category6Cell3.setFont(font)
        self.category6Cell3.setFrameShape(QtGui.QFrame.Box)
        self.category6Cell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6Cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.category6Cell3.setObjectName(_fromUtf8("category6Cell3"))
        self.gridLayout_2.addWidget(self.category6Cell3, 4, 5, 1, 1)
        self.category6Cell1 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6Cell1.sizePolicy().hasHeightForWidth())
        self.category6Cell1.setSizePolicy(sizePolicy)
        self.category6Cell1.setMinimumSize(QtCore.QSize(80, 40))
        self.category6Cell1.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category6Cell1.setFont(font)
        self.category6Cell1.setFrameShape(QtGui.QFrame.Box)
        self.category6Cell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6Cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.category6Cell1.setObjectName(_fromUtf8("category6Cell1"))
        self.gridLayout_2.addWidget(self.category6Cell1, 2, 5, 1, 1)
        self.category5Cell4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5Cell4.sizePolicy().hasHeightForWidth())
        self.category5Cell4.setSizePolicy(sizePolicy)
        self.category5Cell4.setMinimumSize(QtCore.QSize(80, 40))
        self.category5Cell4.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category5Cell4.setFont(font)
        self.category5Cell4.setFrameShape(QtGui.QFrame.Box)
        self.category5Cell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5Cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.category5Cell4.setObjectName(_fromUtf8("category5Cell4"))
        self.gridLayout_2.addWidget(self.category5Cell4, 5, 4, 1, 1)
        self.category5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5.sizePolicy().hasHeightForWidth())
        self.category5.setSizePolicy(sizePolicy)
        self.category5.setMinimumSize(QtCore.QSize(80, 50))
        self.category5.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.category5.setFont(font)
        self.category5.setFrameShape(QtGui.QFrame.Box)
        self.category5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5.setScaledContents(True)
        self.category5.setAlignment(QtCore.Qt.AlignCenter)
        self.category5.setWordWrap(True)
        self.category5.setIndent(1)
        self.category5.setObjectName(_fromUtf8("category5"))
        self.gridLayout_2.addWidget(self.category5, 0, 4, 1, 1)
        self.category5Cell1 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category5Cell1.sizePolicy().hasHeightForWidth())
        self.category5Cell1.setSizePolicy(sizePolicy)
        self.category5Cell1.setMinimumSize(QtCore.QSize(80, 40))
        self.category5Cell1.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category5Cell1.setFont(font)
        self.category5Cell1.setFrameShape(QtGui.QFrame.Box)
        self.category5Cell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category5Cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.category5Cell1.setObjectName(_fromUtf8("category5Cell1"))
        self.gridLayout_2.addWidget(self.category5Cell1, 2, 4, 1, 1)
        self.category3Cell4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3Cell4.sizePolicy().hasHeightForWidth())
        self.category3Cell4.setSizePolicy(sizePolicy)
        self.category3Cell4.setMinimumSize(QtCore.QSize(80, 40))
        self.category3Cell4.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category3Cell4.setFont(font)
        self.category3Cell4.setFrameShape(QtGui.QFrame.Box)
        self.category3Cell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3Cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.category3Cell4.setObjectName(_fromUtf8("category3Cell4"))
        self.gridLayout_2.addWidget(self.category3Cell4, 5, 2, 1, 1)
        self.category3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3.sizePolicy().hasHeightForWidth())
        self.category3.setSizePolicy(sizePolicy)
        self.category3.setMinimumSize(QtCore.QSize(80, 50))
        self.category3.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.category3.setFont(font)
        self.category3.setFrameShape(QtGui.QFrame.Box)
        self.category3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3.setScaledContents(True)
        self.category3.setAlignment(QtCore.Qt.AlignCenter)
        self.category3.setWordWrap(True)
        self.category3.setIndent(1)
        self.category3.setObjectName(_fromUtf8("category3"))
        self.gridLayout_2.addWidget(self.category3, 0, 2, 1, 1)
        self.category2Cell2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2Cell2.sizePolicy().hasHeightForWidth())
        self.category2Cell2.setSizePolicy(sizePolicy)
        self.category2Cell2.setMinimumSize(QtCore.QSize(80, 40))
        self.category2Cell2.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category2Cell2.setFont(font)
        self.category2Cell2.setFrameShape(QtGui.QFrame.Box)
        self.category2Cell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2Cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.category2Cell2.setObjectName(_fromUtf8("category2Cell2"))
        self.gridLayout_2.addWidget(self.category2Cell2, 3, 1, 1, 1)
        self.category3Cell3 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category3Cell3.sizePolicy().hasHeightForWidth())
        self.category3Cell3.setSizePolicy(sizePolicy)
        self.category3Cell3.setMinimumSize(QtCore.QSize(80, 40))
        self.category3Cell3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category3Cell3.setFont(font)
        self.category3Cell3.setFrameShape(QtGui.QFrame.Box)
        self.category3Cell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.category3Cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.category3Cell3.setObjectName(_fromUtf8("category3Cell3"))
        self.gridLayout_2.addWidget(self.category3Cell3, 4, 2, 1, 1)
        self.category4Cell4 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category4Cell4.sizePolicy().hasHeightForWidth())
        self.category4Cell4.setSizePolicy(sizePolicy)
        self.category4Cell4.setMinimumSize(QtCore.QSize(80, 40))
        self.category4Cell4.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category4Cell4.setFont(font)
        self.category4Cell4.setFrameShape(QtGui.QFrame.Box)
        self.category4Cell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.category4Cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.category4Cell4.setObjectName(_fromUtf8("category4Cell4"))
        self.gridLayout_2.addWidget(self.category4Cell4, 5, 3, 1, 1)
        self.category1 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1.sizePolicy().hasHeightForWidth())
        self.category1.setSizePolicy(sizePolicy)
        self.category1.setMinimumSize(QtCore.QSize(80, 50))
        self.category1.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.category1.setFont(font)
        self.category1.setFrameShape(QtGui.QFrame.Box)
        self.category1.setFrameShadow(QtGui.QFrame.Sunken)
        self.category1.setScaledContents(True)
        self.category1.setAlignment(QtCore.Qt.AlignCenter)
        self.category1.setWordWrap(True)
        self.category1.setIndent(1)
        self.category1.setObjectName(_fromUtf8("category1"))
        self.gridLayout_2.addWidget(self.category1, 0, 0, 1, 1)
        self.category2Cell5 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2Cell5.sizePolicy().hasHeightForWidth())
        self.category2Cell5.setSizePolicy(sizePolicy)
        self.category2Cell5.setMinimumSize(QtCore.QSize(80, 40))
        self.category2Cell5.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category2Cell5.setFont(font)
        self.category2Cell5.setFrameShape(QtGui.QFrame.Box)
        self.category2Cell5.setFrameShadow(QtGui.QFrame.Sunken)
        self.category2Cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.category2Cell5.setObjectName(_fromUtf8("category2Cell5"))
        self.gridLayout_2.addWidget(self.category2Cell5, 6, 1, 1, 1)
        self.category6Cell2 = QtGui.QLabel(self.jeopardyMatrix)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category6Cell2.sizePolicy().hasHeightForWidth())
        self.category6Cell2.setSizePolicy(sizePolicy)
        self.category6Cell2.setMinimumSize(QtCore.QSize(80, 40))
        self.category6Cell2.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.category6Cell2.setFont(font)
        self.category6Cell2.setFrameShape(QtGui.QFrame.Box)
        self.category6Cell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.category6Cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.category6Cell2.setObjectName(_fromUtf8("category6Cell2"))
        self.gridLayout_2.addWidget(self.category6Cell2, 3, 5, 1, 1)
        self.questionsContestantsLayout.addWidget(self.jeopardyMatrix)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.questionsContestantsLayout.addItem(spacerItem1)
        self.playerScores = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerScores.sizePolicy().hasHeightForWidth())
        self.playerScores.setSizePolicy(sizePolicy)
        self.playerScores.setMaximumSize(QtCore.QSize(600, 200))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.playerScores.setFont(font)
        self.playerScores.setFrameShape(QtGui.QFrame.Box)
        self.playerScores.setFrameShadow(QtGui.QFrame.Sunken)
        self.playerScores.setLineWidth(3)
        self.playerScores.setObjectName(_fromUtf8("playerScores"))
        self.gridLayout = QtGui.QGridLayout(self.playerScores)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.player1Tokens = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player1Tokens.sizePolicy().hasHeightForWidth())
        self.player1Tokens.setSizePolicy(sizePolicy)
        self.player1Tokens.setMinimumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player1Tokens.setFont(font)
        self.player1Tokens.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Tokens.setObjectName(_fromUtf8("player1Tokens"))
        self.gridLayout.addWidget(self.player1Tokens, 7, 0, 1, 1)
        self.player3Name = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player3Name.sizePolicy().hasHeightForWidth())
        self.player3Name.setSizePolicy(sizePolicy)
        self.player3Name.setMinimumSize(QtCore.QSize(200, 20))
        self.player3Name.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player3Name.setFont(font)
        self.player3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Name.setObjectName(_fromUtf8("player3Name"))
        self.gridLayout.addWidget(self.player3Name, 2, 2, 1, 1)
        self.contestantsLabel = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contestantsLabel.sizePolicy().hasHeightForWidth())
        self.contestantsLabel.setSizePolicy(sizePolicy)
        self.contestantsLabel.setMinimumSize(QtCore.QSize(200, 30))
        self.contestantsLabel.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.contestantsLabel.setFont(font)
        self.contestantsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contestantsLabel.setObjectName(_fromUtf8("contestantsLabel"))
        self.gridLayout.addWidget(self.contestantsLabel, 0, 1, 1, 1)
        self.player2Score = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player2Score.sizePolicy().hasHeightForWidth())
        self.player2Score.setSizePolicy(sizePolicy)
        self.player2Score.setMinimumSize(QtCore.QSize(200, 20))
        self.player2Score.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player2Score.setFont(font)
        self.player2Score.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Score.setObjectName(_fromUtf8("player2Score"))
        self.gridLayout.addWidget(self.player2Score, 5, 1, 1, 1)
        self.player2Name = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player2Name.sizePolicy().hasHeightForWidth())
        self.player2Name.setSizePolicy(sizePolicy)
        self.player2Name.setMinimumSize(QtCore.QSize(200, 20))
        self.player2Name.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player2Name.setFont(font)
        self.player2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Name.setObjectName(_fromUtf8("player2Name"))
        self.gridLayout.addWidget(self.player2Name, 2, 1, 1, 1)
        self.player1Score = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player1Score.sizePolicy().hasHeightForWidth())
        self.player1Score.setSizePolicy(sizePolicy)
        self.player1Score.setMinimumSize(QtCore.QSize(200, 20))
        self.player1Score.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player1Score.setFont(font)
        self.player1Score.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Score.setObjectName(_fromUtf8("player1Score"))
        self.gridLayout.addWidget(self.player1Score, 5, 0, 1, 1)
        self.tokenLabel = QtGui.QLabel(self.playerScores)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tokenLabel.setFont(font)
        self.tokenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tokenLabel.setObjectName(_fromUtf8("tokenLabel"))
        self.gridLayout.addWidget(self.tokenLabel, 6, 0, 1, 3)
        self.line = QtGui.QFrame(self.playerScores)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.player1Name = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player1Name.sizePolicy().hasHeightForWidth())
        self.player1Name.setSizePolicy(sizePolicy)
        self.player1Name.setMinimumSize(QtCore.QSize(200, 20))
        self.player1Name.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player1Name.setFont(font)
        self.player1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Name.setObjectName(_fromUtf8("player1Name"))
        self.gridLayout.addWidget(self.player1Name, 2, 0, 1, 1)
        self.pointsLabel = QtGui.QLabel(self.playerScores)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pointsLabel.setFont(font)
        self.pointsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pointsLabel.setObjectName(_fromUtf8("pointsLabel"))
        self.gridLayout.addWidget(self.pointsLabel, 3, 0, 2, 3)
        self.player3Score = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player3Score.sizePolicy().hasHeightForWidth())
        self.player3Score.setSizePolicy(sizePolicy)
        self.player3Score.setMinimumSize(QtCore.QSize(200, 20))
        self.player3Score.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player3Score.setFont(font)
        self.player3Score.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Score.setObjectName(_fromUtf8("player3Score"))
        self.gridLayout.addWidget(self.player3Score, 5, 2, 1, 1)
        self.player2Tokens = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player2Tokens.sizePolicy().hasHeightForWidth())
        self.player2Tokens.setSizePolicy(sizePolicy)
        self.player2Tokens.setMinimumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player2Tokens.setFont(font)
        self.player2Tokens.setAlignment(QtCore.Qt.AlignCenter)
        self.player2Tokens.setObjectName(_fromUtf8("player2Tokens"))
        self.gridLayout.addWidget(self.player2Tokens, 7, 1, 1, 1)
        self.player3Tokens = QtGui.QLabel(self.playerScores)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player3Tokens.sizePolicy().hasHeightForWidth())
        self.player3Tokens.setSizePolicy(sizePolicy)
        self.player3Tokens.setMinimumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player3Tokens.setFont(font)
        self.player3Tokens.setAlignment(QtCore.Qt.AlignCenter)
        self.player3Tokens.setObjectName(_fromUtf8("player3Tokens"))
        self.gridLayout.addWidget(self.player3Tokens, 7, 2, 1, 1)
        self.questionsContestantsLayout.addWidget(self.playerScores)
        spacerItem2 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.questionsContestantsLayout.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.timeRemainingLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.timeRemainingLabel.setFont(font)
        self.timeRemainingLabel.setObjectName(_fromUtf8("timeRemainingLabel"))
        self.horizontalLayout.addWidget(self.timeRemainingLabel)
        self.timeRemainingValue = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.timeRemainingValue.setFont(font)
        self.timeRemainingValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeRemainingValue.setObjectName(_fromUtf8("timeRemainingValue"))
        self.horizontalLayout.addWidget(self.timeRemainingValue)
        self.questionsContestantsLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.questionsContestantsLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.wheelWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wheelWidget.sizePolicy().hasHeightForWidth())
        self.wheelWidget.setSizePolicy(sizePolicy)
        self.wheelWidget.setObjectName(_fromUtf8("wheelWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.wheelWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.indicatorLabel = QtGui.QLabel(self.wheelWidget)
        self.indicatorLabel.setText(_fromUtf8(""))
        self.indicatorLabel.setPixmap(QtGui.QPixmap(_fromUtf8("../../indicator.png")))
        self.indicatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.indicatorLabel.setObjectName(_fromUtf8("indicatorLabel"))
        self.verticalLayout_6.addWidget(self.indicatorLabel)
        self.wheelView = QtGui.QGraphicsView(self.wheelWidget)
        self.wheelView.setStyleSheet(_fromUtf8("background: transparent"))
        self.wheelView.setFrameShape(QtGui.QFrame.NoFrame)
        self.wheelView.setFrameShadow(QtGui.QFrame.Plain)
        self.wheelView.setLineWidth(0)
        self.wheelView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wheelView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wheelView.setObjectName(_fromUtf8("wheelView"))
        self.verticalLayout_6.addWidget(self.wheelView)
        self.verticalLayout_2.addWidget(self.wheelWidget)
        self.spinButtonLayout = QtGui.QWidget(self.centralwidget)
        self.spinButtonLayout.setMaximumSize(QtCore.QSize(16777215, 40))
        self.spinButtonLayout.setObjectName(_fromUtf8("spinButtonLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.spinButtonLayout)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.spinButton = QtGui.QPushButton(self.spinButtonLayout)
        self.spinButton.setMinimumSize(QtCore.QSize(100, 33))
        self.spinButton.setMaximumSize(QtCore.QSize(100, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.spinButton.setFont(font)
        self.spinButton.setObjectName(_fromUtf8("spinButton"))
        self.horizontalLayout_3.addWidget(self.spinButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.spinButtonLayout)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(400, 40))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spinCountLabel = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCountLabel.sizePolicy().hasHeightForWidth())
        self.spinCountLabel.setSizePolicy(sizePolicy)
        self.spinCountLabel.setMaximumSize(QtCore.QSize(225, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinCountLabel.setFont(font)
        self.spinCountLabel.setObjectName(_fromUtf8("spinCountLabel"))
        self.horizontalLayout_4.addWidget(self.spinCountLabel)
        self.spinCountValue = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCountValue.sizePolicy().hasHeightForWidth())
        self.spinCountValue.setSizePolicy(sizePolicy)
        self.spinCountValue.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinCountValue.setFont(font)
        self.spinCountValue.setObjectName(_fromUtf8("spinCountValue"))
        self.horizontalLayout_4.addWidget(self.spinCountValue)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.widget)
        self.answerLayout = QtGui.QHBoxLayout()
        self.answerLayout.setObjectName(_fromUtf8("answerLayout"))
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.answerLayout.addItem(spacerItem6)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(275, 0))
        self.frame.setMaximumSize(QtCore.QSize(275, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(3)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sectorOutput = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sectorOutput.setFont(font)
        self.sectorOutput.setWordWrap(True)
        self.sectorOutput.setObjectName(_fromUtf8("sectorOutput"))
        self.horizontalLayout_2.addWidget(self.sectorOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.currentQuestion = QtGui.QLabel(self.frame)
        self.currentQuestion.setMinimumSize(QtCore.QSize(200, 75))
        self.currentQuestion.setMaximumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.currentQuestion.setFont(font)
        self.currentQuestion.setScaledContents(True)
        self.currentQuestion.setAlignment(QtCore.Qt.AlignCenter)
        self.currentQuestion.setWordWrap(True)
        self.currentQuestion.setObjectName(_fromUtf8("currentQuestion"))
        self.verticalLayout_3.addWidget(self.currentQuestion)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.playerAnswerLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.playerAnswerLabel.setFont(font)
        self.playerAnswerLabel.setObjectName(_fromUtf8("playerAnswerLabel"))
        self.verticalLayout.addWidget(self.playerAnswerLabel)
        self.playerAnswerEntryBox = QtGui.QTextEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.playerAnswerEntryBox.sizePolicy().hasHeightForWidth())
        self.playerAnswerEntryBox.setSizePolicy(sizePolicy)
        self.playerAnswerEntryBox.setMinimumSize(QtCore.QSize(200, 100))
        self.playerAnswerEntryBox.setMaximumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.playerAnswerEntryBox.setFont(font)
        self.playerAnswerEntryBox.setObjectName(_fromUtf8("playerAnswerEntryBox"))
        self.verticalLayout.addWidget(self.playerAnswerEntryBox)
        self.submitAnswerButton = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.submitAnswerButton.setFont(font)
        self.submitAnswerButton.setObjectName(_fromUtf8("submitAnswerButton"))
        self.verticalLayout.addWidget(self.submitAnswerButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.answerLayout.addWidget(self.frame)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.answerLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.answerLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        WojApplicationWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(WojApplicationWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuEdit_player_names = QtGui.QMenu(self.menuOptions)
        self.menuEdit_player_names.setObjectName(_fromUtf8("menuEdit_player_names"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        WojApplicationWindow.setMenuBar(self.menuBar)
        self.actionClose = QtGui.QAction(WojApplicationWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionEdit_questions_answers = QtGui.QAction(WojApplicationWindow)
        self.actionEdit_questions_answers.setObjectName(_fromUtf8("actionEdit_questions_answers"))
        self.actionPlayer1 = QtGui.QAction(WojApplicationWindow)
        self.actionPlayer1.setObjectName(_fromUtf8("actionPlayer1"))
        self.actionPlayer2 = QtGui.QAction(WojApplicationWindow)
        self.actionPlayer2.setObjectName(_fromUtf8("actionPlayer2"))
        self.actionPlayer3 = QtGui.QAction(WojApplicationWindow)
        self.actionPlayer3.setObjectName(_fromUtf8("actionPlayer3"))
        self.menuEdit_player_names.addAction(self.actionPlayer1)
        self.menuEdit_player_names.addAction(self.actionPlayer2)
        self.menuEdit_player_names.addAction(self.actionPlayer3)
        self.menuOptions.addAction(self.actionEdit_questions_answers)
        self.menuOptions.addAction(self.menuEdit_player_names.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.player1Name.setBuddy(self.playerScores)

        self.retranslateUi(WojApplicationWindow)
        QtCore.QMetaObject.connectSlotsByName(WojApplicationWindow)

    def retranslateUi(self, WojApplicationWindow):
        WojApplicationWindow.setWindowTitle(_translate("WojApplicationWindow", "MainWindow", None))
        self.applicationTitle.setText(_translate("WojApplicationWindow", "Wheel Of Jeopardy!", None))
        self.category2Cell3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category6Cell5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category6.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category5Cell5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category3Cell5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category4Cell1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category3Cell1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category2Cell1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category1Cell3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category4Cell5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category4Cell3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category1Cell5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category5Cell3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category4Cell2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category1Cell2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category2Cell4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category6Cell4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category1Cell1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category1Cell4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category5Cell2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category3Cell2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category6Cell3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category6Cell1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category5Cell4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category5Cell1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category3Cell4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category2Cell2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category3Cell3.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category4Cell4.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category1.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category2Cell5.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.category6Cell2.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.player1Tokens.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.player3Name.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.contestantsLabel.setText(_translate("WojApplicationWindow", "Today\'s Contestants", None))
        self.player2Score.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.player2Name.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.player1Score.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.tokenLabel.setText(_translate("WojApplicationWindow", "Token Count:", None))
        self.player1Name.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.pointsLabel.setText(_translate("WojApplicationWindow", "Current Points:", None))
        self.player3Score.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.player2Tokens.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.player3Tokens.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.timeRemainingLabel.setText(_translate("WojApplicationWindow", "Time Remaining:", None))
        self.timeRemainingValue.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.spinButton.setText(_translate("WojApplicationWindow", "SPIN!", None))
        self.spinCountLabel.setText(_translate("WojApplicationWindow", "Spins Remaining:", None))
        self.spinCountValue.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.label_2.setText(_translate("WojApplicationWindow", "Category:", None))
        self.sectorOutput.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.currentQuestion.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.playerAnswerLabel.setText(_translate("WojApplicationWindow", "TextLabel", None))
        self.submitAnswerButton.setText(_translate("WojApplicationWindow", "SUBMIT ANSWER", None))
        self.menuOptions.setTitle(_translate("WojApplicationWindow", "WoJ Options", None))
        self.menuEdit_player_names.setTitle(_translate("WojApplicationWindow", "Edit player settings", None))
        self.menuFile.setTitle(_translate("WojApplicationWindow", "File", None))
        self.actionClose.setText(_translate("WojApplicationWindow", "Close", None))
        self.actionEdit_questions_answers.setText(_translate("WojApplicationWindow", "Edit questions & answers", None))
        self.actionPlayer1.setText(_translate("WojApplicationWindow", "Player1", None))
        self.actionPlayer2.setText(_translate("WojApplicationWindow", "Player2", None))
        self.actionPlayer3.setText(_translate("WojApplicationWindow", "Player3", None))

