'''
This class brings up the choose category popup when WojApplication runs show_category_popup()

@author = Miranda Link, mirandanlink@gmail.com
'''

# imports
#
import CategoryDialog # this is the .py file which is generated by pyQt

class ActivateCategoryPopup(QDialog, CategoryDialog.Ui_CategoryDialog):
	def __init__(self, parent=None): # need parent probably?
		super(ActivateCategoryPopup, self).__init__(parent)
		self.setupUi(self)

		# initialize variables
		#
		self.category1Label.setText(category1)
		self.category2Label.setText(category2)
		self.category3Label.setText(category3)
		self.category4Label.setText(category4)
		self.category5Label.setText(category5)
		self.category6Label.setText(category6)

	# button clicks
	#
	@pyqtSignature("")
	def on_category1_clicked(self):
		self.broadcast('category_chosen', 1)

	@pyqtSignature("")
	def on_category1_clicked(self):
		self.broadcast('category_chosen', 2)

	@pyqtSignature("")
	def on_category1_clicked(self):
		self.broadcast('category_chosen', 3)

	@pyqtSignature("")
	def on_category1_clicked(self):
		self.broadcast('category_chosen', 4)

	@pyqtSignature("")
	def on_category1_clicked(self):
		self.broadcast('category_chosen', 5)

	@pyqtSignature("")
	def on_category1_clicked(self):
		self.broadcast('category_chosen', 6)



